// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: recon/jobmgmt/config.proto

package jobmgmt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// add single/multi logs
type ReadConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job     string `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"` // original job id - leave it empty if new
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ReadConfigRequest) Reset() {
	*x = ReadConfigRequest{}
	mi := &file_recon_jobmgmt_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigRequest) ProtoMessage() {}

func (x *ReadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_jobmgmt_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReadConfigRequest) Descriptor() ([]byte, []int) {
	return file_recon_jobmgmt_config_proto_rawDescGZIP(), []int{0}
}

func (x *ReadConfigRequest) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *ReadConfigRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ReadConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *JobConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ReadConfigResponse) Reset() {
	*x = ReadConfigResponse{}
	mi := &file_recon_jobmgmt_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigResponse) ProtoMessage() {}

func (x *ReadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_jobmgmt_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReadConfigResponse) Descriptor() ([]byte, []int) {
	return file_recon_jobmgmt_config_proto_rawDescGZIP(), []int{1}
}

func (x *ReadConfigResponse) GetConfig() *JobConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_recon_jobmgmt_config_proto protoreflect.FileDescriptor

var file_recon_jobmgmt_config_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x2f, 0x6a, 0x6f, 0x62, 0x6d, 0x67, 0x6d, 0x74, 0x2f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x65,
	0x63, 0x6f, 0x6e, 0x2e, 0x6a, 0x6f, 0x62, 0x6d, 0x67, 0x6d, 0x74, 0x1a, 0x25, 0x72, 0x65, 0x63,
	0x6f, 0x6e, 0x2f, 0x6a, 0x6f, 0x62, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x4f, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x6e, 0x2e, 0x6a, 0x6f, 0x62, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x32, 0x73, 0x0a, 0x1c, 0x4a, 0x6f, 0x62, 0x6d, 0x67, 0x6d, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x20, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x2e, 0x6a, 0x6f, 0x62, 0x6d, 0x67,
	0x6d, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x2e, 0x6a, 0x6f, 0x62,
	0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x72, 0x65, 0x63,
	0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x6a, 0x6f, 0x62, 0x6d, 0x67, 0x6d, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recon_jobmgmt_config_proto_rawDescOnce sync.Once
	file_recon_jobmgmt_config_proto_rawDescData = file_recon_jobmgmt_config_proto_rawDesc
)

func file_recon_jobmgmt_config_proto_rawDescGZIP() []byte {
	file_recon_jobmgmt_config_proto_rawDescOnce.Do(func() {
		file_recon_jobmgmt_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_recon_jobmgmt_config_proto_rawDescData)
	})
	return file_recon_jobmgmt_config_proto_rawDescData
}

var file_recon_jobmgmt_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recon_jobmgmt_config_proto_goTypes = []any{
	(*ReadConfigRequest)(nil),  // 0: recon.jobmgmt.ReadConfigRequest
	(*ReadConfigResponse)(nil), // 1: recon.jobmgmt.ReadConfigResponse
	(*JobConfig)(nil),          // 2: recon.jobmgmt.messages.JobConfig
}
var file_recon_jobmgmt_config_proto_depIdxs = []int32{
	2, // 0: recon.jobmgmt.ReadConfigResponse.config:type_name -> recon.jobmgmt.messages.JobConfig
	0, // 1: recon.jobmgmt.JobmgmtConfigProviderService.ReadConfig:input_type -> recon.jobmgmt.ReadConfigRequest
	1, // 2: recon.jobmgmt.JobmgmtConfigProviderService.ReadConfig:output_type -> recon.jobmgmt.ReadConfigResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recon_jobmgmt_config_proto_init() }
func file_recon_jobmgmt_config_proto_init() {
	if File_recon_jobmgmt_config_proto != nil {
		return
	}
	file_recon_jobmgmt_messages_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recon_jobmgmt_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recon_jobmgmt_config_proto_goTypes,
		DependencyIndexes: file_recon_jobmgmt_config_proto_depIdxs,
		MessageInfos:      file_recon_jobmgmt_config_proto_msgTypes,
	}.Build()
	File_recon_jobmgmt_config_proto = out.File
	file_recon_jobmgmt_config_proto_rawDesc = nil
	file_recon_jobmgmt_config_proto_goTypes = nil
	file_recon_jobmgmt_config_proto_depIdxs = nil
}
