// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: recon/jobmgmt/config.proto

package jobmgmt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobmgmtConfigProviderService_ReadConfig_FullMethodName = "/recon.jobmgmt.JobmgmtConfigProviderService/ReadConfig"
)

// JobmgmtConfigProviderServiceClient is the client API for JobmgmtConfigProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GRPC-only
// in-cluster only
// Provider service to be implemented by config provider service
// clients to be worker microservices
type JobmgmtConfigProviderServiceClient interface {
	// returns config to the caller.
	ReadConfig(ctx context.Context, in *ReadConfigRequest, opts ...grpc.CallOption) (*ReadConfigResponse, error)
}

type jobmgmtConfigProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobmgmtConfigProviderServiceClient(cc grpc.ClientConnInterface) JobmgmtConfigProviderServiceClient {
	return &jobmgmtConfigProviderServiceClient{cc}
}

func (c *jobmgmtConfigProviderServiceClient) ReadConfig(ctx context.Context, in *ReadConfigRequest, opts ...grpc.CallOption) (*ReadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadConfigResponse)
	err := c.cc.Invoke(ctx, JobmgmtConfigProviderService_ReadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobmgmtConfigProviderServiceServer is the server API for JobmgmtConfigProviderService service.
// All implementations should embed UnimplementedJobmgmtConfigProviderServiceServer
// for forward compatibility.
//
// GRPC-only
// in-cluster only
// Provider service to be implemented by config provider service
// clients to be worker microservices
type JobmgmtConfigProviderServiceServer interface {
	// returns config to the caller.
	ReadConfig(context.Context, *ReadConfigRequest) (*ReadConfigResponse, error)
}

// UnimplementedJobmgmtConfigProviderServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobmgmtConfigProviderServiceServer struct{}

func (UnimplementedJobmgmtConfigProviderServiceServer) ReadConfig(context.Context, *ReadConfigRequest) (*ReadConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadConfig not implemented")
}
func (UnimplementedJobmgmtConfigProviderServiceServer) testEmbeddedByValue() {}

// UnsafeJobmgmtConfigProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobmgmtConfigProviderServiceServer will
// result in compilation errors.
type UnsafeJobmgmtConfigProviderServiceServer interface {
	mustEmbedUnimplementedJobmgmtConfigProviderServiceServer()
}

func RegisterJobmgmtConfigProviderServiceServer(s grpc.ServiceRegistrar, srv JobmgmtConfigProviderServiceServer) {
	// If the following call pancis, it indicates UnimplementedJobmgmtConfigProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobmgmtConfigProviderService_ServiceDesc, srv)
}

func _JobmgmtConfigProviderService_ReadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobmgmtConfigProviderServiceServer).ReadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobmgmtConfigProviderService_ReadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobmgmtConfigProviderServiceServer).ReadConfig(ctx, req.(*ReadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobmgmtConfigProviderService_ServiceDesc is the grpc.ServiceDesc for JobmgmtConfigProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobmgmtConfigProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recon.jobmgmt.JobmgmtConfigProviderService",
	HandlerType: (*JobmgmtConfigProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadConfig",
			Handler:    _JobmgmtConfigProviderService_ReadConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recon/jobmgmt/config.proto",
}
