// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: recon/jobmgmt/log.proto

package jobmgmt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobmgmtLogWriterService_CreateLog_FullMethodName = "/recon.jobmgmt.JobmgmtLogWriterService/CreateLog"
)

// JobmgmtLogWriterServiceClient is the client API for JobmgmtLogWriterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GRPC-only
// to be implemented by worker microservices
type JobmgmtLogWriterServiceClient interface {
	CreateLog(ctx context.Context, in *CreateLogRequest, opts ...grpc.CallOption) (*CreateLogResponse, error)
}

type jobmgmtLogWriterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobmgmtLogWriterServiceClient(cc grpc.ClientConnInterface) JobmgmtLogWriterServiceClient {
	return &jobmgmtLogWriterServiceClient{cc}
}

func (c *jobmgmtLogWriterServiceClient) CreateLog(ctx context.Context, in *CreateLogRequest, opts ...grpc.CallOption) (*CreateLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLogResponse)
	err := c.cc.Invoke(ctx, JobmgmtLogWriterService_CreateLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobmgmtLogWriterServiceServer is the server API for JobmgmtLogWriterService service.
// All implementations should embed UnimplementedJobmgmtLogWriterServiceServer
// for forward compatibility.
//
// GRPC-only
// to be implemented by worker microservices
type JobmgmtLogWriterServiceServer interface {
	CreateLog(context.Context, *CreateLogRequest) (*CreateLogResponse, error)
}

// UnimplementedJobmgmtLogWriterServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobmgmtLogWriterServiceServer struct{}

func (UnimplementedJobmgmtLogWriterServiceServer) CreateLog(context.Context, *CreateLogRequest) (*CreateLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLog not implemented")
}
func (UnimplementedJobmgmtLogWriterServiceServer) testEmbeddedByValue() {}

// UnsafeJobmgmtLogWriterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobmgmtLogWriterServiceServer will
// result in compilation errors.
type UnsafeJobmgmtLogWriterServiceServer interface {
	mustEmbedUnimplementedJobmgmtLogWriterServiceServer()
}

func RegisterJobmgmtLogWriterServiceServer(s grpc.ServiceRegistrar, srv JobmgmtLogWriterServiceServer) {
	// If the following call pancis, it indicates UnimplementedJobmgmtLogWriterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobmgmtLogWriterService_ServiceDesc, srv)
}

func _JobmgmtLogWriterService_CreateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobmgmtLogWriterServiceServer).CreateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobmgmtLogWriterService_CreateLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobmgmtLogWriterServiceServer).CreateLog(ctx, req.(*CreateLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobmgmtLogWriterService_ServiceDesc is the grpc.ServiceDesc for JobmgmtLogWriterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobmgmtLogWriterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recon.jobmgmt.JobmgmtLogWriterService",
	HandlerType: (*JobmgmtLogWriterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLog",
			Handler:    _JobmgmtLogWriterService_CreateLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recon/jobmgmt/log.proto",
}
